var interfaceConfig = {
    DISABLE_BROWSER_WARNING: true,
    DISABLE_VIDEO_BACKGROUND: false,
    DISABLE_DOMINANT_SPEAKER_INDICATOR: false,
    DISABLE_FOCUS_INDICATOR: false,
    DISABLE_JOIN_LEAVE_NOTIFICATIONS: false,
    DISABLE_PRESENCE_STATUS: false,
    DISABLE_RINGING: false,
    DISABLE_TRANSCRIPTION_SUBTITLES: false,
    DISABLE_WELCOME_PAGE: false,
    ENABLE_DIAL_OUT: false,
    ENABLE_FILE_UPLOAD: false,
    FILM_STRIP_MAX_HEIGHT: 90,
    INITIAL_TOOLBAR_TIMEOUT: 20000,
    TOOLBAR_TIMEOUT: 4000,
    TOOLBAR_BUTTONS: [
        'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
        'fodeviceselection', 'hangup', 'profile', 'chat', 'recording',
        'livestreaming', 'etherpad', 'sharedvideo', 'settings', 'raisehand',
        'videoquality', 'filmstrip', 'invite', 'feedback', 'stats', 'shortcuts',
        'tileview', 'videobackgroundblur', 'download', 'help', 'mute-everyone',
        'mute-video-everyone', 'security'
    ],
    SETTINGS_SECTIONS: [ 'devices', 'language', 'moderator', 'profile', 'calendar' ],
    SHOW_BRAND_WATERMARK: false,
    SHOW_BRAND_WATERMARK_LINK: '',
    SHOW_DEEP_LINKING_IMAGE: false,
    SHOW_JITSI_WATERMARK: false,
    SHOW_POWERED_BY: false,
    SHOW_PROMOTIONAL_CLOSE_PAGE: false,
    SHOW_WATERMARK_FOR_GUESTS: false,
    SUPPORT_URL: '',
    DEFAULT_BACKGROUND: '#474747',
    DEFAULT_REMOTE_DISPLAY_NAME: 'Fellow Jitster',
    DEFAULT_LOCAL_DISPLAY_NAME: 'me',
    SHOW_WATERMARK: false,
    SHOW_BRAND_WATERMARK: false,
    BRAND_WATERMARK_LINK: '',
    SHOW_DEEP_LINKING_IMAGE: false,
    DISABLE_DOMINANT_SPEAKER_INDICATOR: false,
    DISABLE_PRESENCE_STATUS: false,
    DISABLE_RINGING: false,
    ENABLE_DIAL_OUT: false,
    ENABLE_FILE_UPLOAD: false,
    FILM_STRIP_MAX_HEIGHT: 90,
    INITIAL_TOOLBAR_TIMEOUT: 20000,
    TOOLBAR_TIMEOUT: 4000,
    WHITEBOARD_ENABLED: false,
    CLOSE_PAGE_GUEST_HINT: false,
    DISABLE_VIDEO_BACKGROUND: false,
    DISABLE_JOIN_LEAVE_NOTIFICATIONS: false,
    DISABLE_TRANSCRIPTION_SUBTITLES: false,
    DISABLE_WELCOME_PAGE: false,
    ENABLE_DIAL_OUT: false,
    ENABLE_FILE_UPLOAD: false,
    FILM_STRIP_MAX_HEIGHT: 90,
    INITIAL_TOOLBAR_TIMEOUT: 20000,
    TOOLBAR_TIMEOUT: 4000
};

